# 넘파이 ndarray 개요

In [78]:
import numpy as np

넘파이의 기반 데이터 타입은 ndarray  
ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행 가능

In [75]:
# array()
array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(3,)


In [77]:
array2 = np.array([[1,2,3], [4,5,6]])
print(type(array2))
print(array2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [79]:
array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(1, 3)


In [81]:
# 차원 확인(.dim)
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


# ndarray의 데이터 타입

ndarray내의 데이터 값은 숫자, 문자열, 불 등이 모두 가능  
숫자 : int형(8, 16, 32 bit), unsigned int형(8, 16, 32 bit), float형(16, 32, 64, 128 bit), complex 타입  
ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능

In [84]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


만약 서로 다른 데이터 타입이 섞여있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

In [86]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


서로 다은 데이터 타입이 섞여 있을 경우 데이터 타입이 더 큰 데이터 타입으로 변환  
int형 < 문자열, int형 < float형

In [87]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_int, array_int.dtype)
print(array_float, array_float.dtype)

[1 2 3] int32
[1. 2. 3.] float64


In [88]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [89]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

## arange()

In [90]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


## zeros()

In [91]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


## ones()

In [92]:
one_array = np.ones((3,2))  # dtype 인자의 default 값은 float64
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()

In [93]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [94]:
array2 = array1.reshape(2,5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [95]:
array3 = array1.reshape(5,2)
print(array3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [96]:
# reshape()는 지정된 사이즈로 변경이 불가능하면 오류를 발생

array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

## -1 인자

In [97]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [98]:
array2 = array1.reshape(-1, 5)
print(array2, array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


In [99]:
array3 = array1.reshape(5, -1)
print(array3, array3.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [100]:
# reshape()는 지정된 사이즈로 변경이 불가능하면 오류를 발생

array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

## tolist()

리스트로 변환

In [116]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d)
print('\n')
print(array3d.tolist())

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [117]:
# 3차원 ndarray를 2차원 ndarray로 변환

array5 = array3d.reshape(-1,1)
print(array5)
print(array5.tolist())
print(array5.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [118]:
# 1차원 ndarray를 2차원 ndarray로 변환

array6 = array1.reshape(-1,1)
print(array6)
print(array6.tolist())
print(array6.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

## 단일 값 추출

In [119]:
# 1부터 9까지의 1차원 ndarray 생성

array1 = np.arange(start=1, stop=10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [120]:
# index는 0부터 시작

value = array1[2]
print(value)
print(type(value))

3
<class 'numpy.int32'>


In [121]:
# 인덱스 -1은 맨 뒤의 데이터값을 의미

print(array1[-1])
print(array1[-2])

9
8


In [122]:
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [124]:
# 2차원 ndarray에서 단일 값 추출

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0,0])
print(array2d[0,1])
print(array2d[1,0])
print(array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


## 슬라이싱

In [125]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [126]:
array4 = array1[:3]  # 처음부터 3-1 까지
print(array4)

array5 = array1[3:]  # 3부터 끝까지
print(array5)

array6 = array1[:]   # 처음부터 끝까지
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [127]:
# 2차원 ndarray 슬라이싱

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:
print(array2d[0:2, 0:2])

[[1 2]
 [4 5]]


In [129]:
print(array2d[1:3, 0:3])

[[4 5 6]
 [7 8 9]]


In [130]:
print(array2d[1:3,])

[[4 5 6]
 [7 8 9]]


In [131]:
print(array2d[:, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [132]:
print(array2d[:2, 1:])

[[2 3]
 [5 6]]


In [133]:
print(array2d[:2, 0])

[1 4]


In [137]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환

print(array2d[0], array2d[0].shape)
print(array2d[1], array2d[1].shape)

[1 2 3] (3,)
[4 5 6] (3,)


## 펜시 인덱싱

리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [141]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print(array3)

[3 6]


In [142]:
array4 = array2d[[0,1], 0:2]
print(array4)

[[1 2]
 [4 5]]


In [143]:
array5 = array2d[[0,1]]
print(array5)

[[1 2 3]
 [4 5 6]]


## 불린 인덱싱

조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식

In [144]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]  # True인 값만 할당
print(array3)

[6 7 8 9]


In [146]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [147]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [148]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


# 행렬의 정렬 - sort()와 argsort()

## 행렬정렬

넘파이의 행렬 정렬  
np.sort() : 넘파이에서 sort()를 호출하는 방식, 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환  
ndarray.sort() : 행렬 자체에서 sort()를 호출하는 방식, 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

In [149]:
org_array = np.array([3, 1, 9, 5])
print(org_array)

[3 1 9 5]


In [152]:
# np.sort()로 정렬

sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array) # 원 행렬 그대로 유지

[1 3 5 9]
[3 1 9 5]


In [153]:
# ndarray.sort()로 정렬

sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)  # 원 행렬 변환

None
[1 3 5 9]


In [155]:
# np.sort()로 내림차순 정렬

sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [159]:
# ndarray.sort()로 내림차순 정렬

org_array = np.array([3, 1, 9, 5])
sort_array2_desc = org_array[::-1].sort()
print(sort_array2_desc)
print(org_array)

None
[9 5 3 1]


In [161]:
# 행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우 또는 컬럼 방향으로 정렬을 수행

array2d = np.array([[8,12], [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)  # 로우 방향으로 정렬

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)  # 컬럼 방향으로 정렬

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


## 정렬된 행렬의 인덱스를 반환하기

원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용  
np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [164]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [165]:
# 내림차순 정렬

org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[2 3 0 1]


In [166]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

## 행렬 내적(행렬 곱)

행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능  
A행렬의 열 개수와 B행렬의 행 개수가 동일해야 내적 연산이 가능

In [167]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8], 
              [9,10], 
              [11,12]])

dot_product = np.dot(A, B)
print(dot_product)  # 1x7 + 2x9 + 3x11 = 58, 4x7 + 5x9 + 6x11 = 139

[[ 58  64]
 [139 154]]


## 전치행렬

원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬, np.transpose()를 이용

In [168]:
A = np.array([[1,2], [3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
